import { chat, Message } from '@/ai/flows/advisor-flow';

// Direct Google AI integration without Genkit dependencies
export interface ChatMessage {
  role: 'user' | 'model';
  content: string;
}

export interface ChatRequest {
  history: ChatMessage[];
  prompt: string;
  userId?: string;
}

// Mock data for AI responses
const scholarships = [
  { name: "Future Leaders Grant", provider: "Tech Innovators Foundation", amount: 5000, minEduscore: 85 },
  { name: "Creative Minds Scholarship", provider: "Arts & Culture Council", amount: 3000, minEduscore: 75 },
  { name: "STEM Achievers Award", provider: "Science & Eng. Society", amount: 10000, minEduscore: 90 },
  { name: "Community First Scholarship", provider: "Local Goodwill Org", amount: 2000, minEduscore: 70 },
  { name: "Phoenix Scholars Program", provider: "Rise Up Foundation", amount: 7500, minEduscore: 80 },
];

const courses = [
  { title: "Web Development Bootcamp", category: "Technology", price: "Paid", rating: 4.8 },
  { title: "Introduction to Business", category: "Business", price: "Free", rating: 4.5 },
  { title: "Graphic Design Masterclass", category: "Design", price: "Paid", rating: 4.9 },
  { title: "Data Science with Python", category: "Technology", price: "Paid", rating: 4.7 },
  { title: "UI/UX Design Fundamentals", category: "Design", price: "Free", rating: 4.7 },
];

const jobs = [
  { title: "Junior Web Developer Intern", company: "Innovatech Solutions", location: "Remote", type: "Internship" },
  { title: "Marketing Assistant (Part-Time)", company: "Growth Wizards", location: "New York, NY", type: "Part-Time" },
  { title: "Data Analyst Intern", company: "DataDriven Inc.", location: "San Francisco, CA", type: "Internship" },
  { title: "Graphic Design Intern", company: "Creative Minds Agency", location: "Remote", type: "Internship" },
];

async function callGoogleAI(messages: any[], apiKey: string): Promise<string> {
  try {
    console.log('Calling Google AI API with', messages.length, 'messages');
    
    // Filter out system messages and format properly for Gemini
    const formattedContents = messages
      .filter(msg => msg.content && msg.content.trim().length > 0)
      .map(msg => ({
        role: msg.role === 'model' ? 'model' : 'user',
        parts: [{ text: msg.content }]
      }));

    console.log('Formatted', formattedContents.length, 'messages for Gemini API');

    const requestBody = {
      contents: formattedContents,
      generationConfig: {
        temperature: 0.8,
        topK: 40,
        topP: 0.95,
        maxOutputTokens: 2048, // Increased for longer responses
        candidateCount: 1
      },
      safetySettings: [
        {
          category: "HARM_CATEGORY_HARASSMENT",
          threshold: "BLOCK_MEDIUM_AND_ABOVE"
        },
        {
          category: "HARM_CATEGORY_HATE_SPEECH", 
          threshold: "BLOCK_MEDIUM_AND_ABOVE"
        },
        {
          category: "HARM_CATEGORY_SEXUALLY_EXPLICIT",
          threshold: "BLOCK_MEDIUM_AND_ABOVE"
        },
        {
          category: "HARM_CATEGORY_DANGEROUS_CONTENT",
          threshold: "BLOCK_MEDIUM_AND_ABOVE"
        }
      ]
    };

    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody)
    });

    console.log('Gemini API response status:', response.status);

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Gemini API error response:', errorText);
      throw new Error(`Google AI API error: ${response.status} - ${errorText}`);
    }

    const data = await response.json();
    console.log('Gemini API response data structure:', {
      hasCandidates: !!data.candidates,
      candidateCount: data.candidates?.length,
      hasContent: !!data.candidates?.[0]?.content,
      hasText: !!data.candidates?.[0]?.content?.parts?.[0]?.text
    });

    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!generatedText) {
      console.error('No text in Gemini response:', data);
      throw new Error('No text generated by Gemini API');
    }

    console.log('Successfully generated text length:', generatedText.length);
    return generatedText;

  } catch (error) {
    console.error('Google AI API Error:', error);
    console.error('Error stack:', error.stack);
    throw error;
  }
}

function generateEnhancedResponse(prompt: string, history: ChatMessage[], eduscoreContext: any): string {
  const lowerPrompt = prompt.toLowerCase();
  
  // Analyze conversation context
  const previousTopics = history
    .filter(msg => msg.role === 'user')
    .map(msg => msg.content.toLowerCase())
    .join(' ');
    
  const hasDiscussedScholarships = previousTopics.includes('scholarship') || previousTopics.includes('học bổng');
  const hasDiscussedJobs = previousTopics.includes('job') || previousTopics.includes('việc làm') || previousTopics.includes('career');
  const hasDiscussedFinance = previousTopics.includes('money') || previousTopics.includes('financial') || previousTopics.includes('loan') || previousTopics.includes('tiền');

  // Financial topics - enhanced responses
  if (lowerPrompt.includes('financial') || lowerPrompt.includes('money') || lowerPrompt.includes('budget') || lowerPrompt.includes('investment') || lowerPrompt.includes('loan') || lowerPrompt.includes('save') || lowerPrompt.includes('bank')) {
    let response = `Tôi rất vui được tư vấn tài chính cho bạn! Dựa trên tình hình kinh tế Việt Nam hiện tại, có nhiều cơ hội tài chính thú vị cho sinh viên.\n\n`;
    
    if (lowerPrompt.includes('loan') || lowerPrompt.includes('vay')) {
      response += `**Về vay học tập:**\n`;
      response += `- BIDV có gói vay sinh viên lãi suất chỉ 6.5%/năm, thấp nhất thị trường\n`;
      response += `- Vietcombank cung cấp vay lên đến 500 triệu VND với thời hạn 15 năm\n`;
      response += `- VPBank có ưu đãi ân hạn gốc trong suốt thời gian học\n\n`;
      response += `Với ${eduscoreContext?.eduscore || 'điểm EduScore'} của bạn, bạn có thể đủ điều kiện cho các gói vay ưu đãi. `;
    } else if (lowerPrompt.includes('invest') || lowerPrompt.includes('đầu tư')) {
      response += `**Về đầu tư cho sinh viên:**\n`;
      response += `- Tiết kiệm có kỳ hạn: Lãi suất 5.5-6.5%/năm, an toàn tuyệt đối\n`;
      response += `- Quỹ mở VCBF, VFMVF1: Lợi nhuận trung bình 10-12%/năm\n`;
      response += `- Chứng khoán: VN-Index đã tăng 12% từ đầu năm, cổ phiếu như VCB, VIC, FPT ổn định\n\n`;
    } else {
      response += `**Tư vấn ngân sách sinh viên:**\n`;
      response += `- Chi phí sinh hoạt trung bình tại HCM/HN: 6-8 triệu VND/tháng\n`;
      response += `- Áp dụng quy tắc 50/30/20: 50% cần thiết, 30% giải trí, 20% tiết kiệm\n`;
      response += `- Với lương part-time 4-6 triệu, bạn vẫn có thể tiết kiệm 800k-1.2 triệu/tháng\n\n`;
    }
    
    response += `Bạn đang quan tâm đến khía cạnh nào cụ thể? Tôi có thể phân tích chi tiết hơn về lãi suất, rủi ro, hay cách thức đăng ký. `;
    if (eduscoreContext?.major) {
      response += `Với chuyên ngành ${eduscoreContext.major}, tôi cũng có thể đưa ra lời khuyên tài chính phù hợp với triển vọng nghề nghiệp của bạn.`;
    }
    
    return response;
  }

  // Scholarship responses
  if (lowerPrompt.includes('scholarship') || lowerPrompt.includes('học bổng') || lowerPrompt.includes('funding')) {
    const eligibleScholarships = eduscoreContext?.eduscore 
      ? scholarships.filter(s => s.minEduscore <= eduscoreContext.eduscore)
      : scholarships.slice(0, 4);
    
    let response = hasDiscussedScholarships 
      ? `Tôi thấy bạn vẫn quan tâm đến học bổng! Để bổ sung thêm cho cuộc trò chuyện trước, ` 
      : `Tuyệt vời! Học bổng là cơ hội tuyệt vời để giảm gánh nặng tài chính. `;
      
    if (eduscoreContext?.eduscore) {
      response += `Với EduScore ${eduscoreContext.eduscore}/100 của bạn, `;
      if (eduscoreContext.eduscore >= 85) {
        response += `bạn đủ điều kiện cho hầu hết các học bổng danh giá!\n\n`;
      } else if (eduscoreContext.eduscore >= 75) {
        response += `bạn có cơ hội tốt với nhiều học bổng!\n\n`;
      } else {
        response += `bạn vẫn có thể đăng ký một số học bổng và nên cải thiện EduScore.\n\n`;
      }
    }
    
    response += `**Học bổng phù hợp:**\n`;
    eligibleScholarships.forEach((scholarship, index) => {
      response += `${index + 1}. **${scholarship.name}** (${scholarship.provider})\n`;
      response += `   💰 Giá trị: ${scholarship.amount.toLocaleString()} USD\n`;
      response += `   📊 EduScore tối thiểu: ${scholarship.minEduscore}\n\n`;
    });
    
    response += `Bạn có muốn tôi hướng dẫn cụ thể cách chuẩn bị hồ sơ cho học bổng nào không? `;
    if (eduscoreContext?.major) {
      response += `Tôi cũng có thể tư vấn thêm về học bổng chuyên ngành ${eduscoreContext.major}.`;
    }
    
    return response;
  }

  // Job and career responses  
  if (lowerPrompt.includes('job') || lowerPrompt.includes('career') || lowerPrompt.includes('việc làm') || lowerPrompt.includes('nghề nghiệp') || lowerPrompt.includes('internship')) {
    let response = hasDiscussedJobs 
      ? `Tôi thấy bạn tiếp tục quan tâm đến cơ hội nghề nghiệp! ` 
      : `Rất tốt khi bạn quan tâm đến định hướng nghề nghiệp! `;
      
    if (eduscoreContext?.major) {
      response += `Với chuyên ngành ${eduscoreContext.major}, thị trường hiện tại có nhiều cơ hội thú vị.\n\n`;
      
      if (eduscoreContext.major.toLowerCase().includes('technology') || eduscoreContext.major.toLowerCase().includes('computer')) {
        response += `**Cơ hội IT tại Việt Nam:**\n`;
        response += `- Junior Developer: 15-25 triệu VND (FPT, TMA, Vng)\n`;
        response += `- Fresher lương cao: 20-35 triệu VND (Google, Microsoft, Shopee)\n`;
        response += `- Remote work: Thu nhập USD, 1000-2500$/tháng\n\n`;
      } else if (eduscoreContext.major.toLowerCase().includes('business') || eduscoreContext.major.toLowerCase().includes('marketing')) {
        response += `**Cơ hội kinh doanh:**\n`;
        response += `- Marketing Executive: 12-20 triệu VND (Unilever, P&G)\n`;
        response += `- Business Analyst: 18-30 triệu VND (các ngân hàng lớn)\n`;
        response += `- Sales Manager: 15-25 triệu + hoa hồng\n\n`;
      }
    } else {
      response += `Dưới đây là một số cơ hội việc làm phổ biến:\n\n`;
      jobs.slice(0, 4).forEach((job, index) => {
        response += `${index + 1}. **${job.title}** tại ${job.company}\n`;
        response += `   📍 ${job.location} | 💰 ${job.salary}\n`;
        response += `   🏷️ ${job.tags.join(', ')}\n\n`;
      });
    }
    
    response += `Bạn muốn tập trung vào loại công việc nào? Tôi có thể tư vấn về cách chuẩn bị CV, phỏng vấn, `;
    if (eduscoreContext?.technicalSkills?.length > 0) {
      response += `hoặc phát triển thêm kỹ năng từ ${eduscoreContext.technicalSkills.join(', ')} hiện tại của bạn.`;
    } else {
      response += `hoặc các kỹ năng cần thiết cho ngành bạn quan tâm.`;
    }
    
    return response;
  }

  // Course and education responses
  if (lowerPrompt.includes('course') || lowerPrompt.includes('learn') || lowerPrompt.includes('study') || lowerPrompt.includes('khóa học') || lowerPrompt.includes('học')) {
    let response = `Học hỏi không ngừng là chìa khóa thành công! `;
    
    if (eduscoreContext?.careerGoals) {
      response += `Với mục tiêu ${eduscoreContext.careerGoals} của bạn, tôi khuyên nên tập trung vào:\n\n`;
    } else {
      response += `Dưới đây là các khóa học phổ biến hiện tại:\n\n`;
    }
    
    courses.slice(0, 5).forEach((course, index) => {
      response += `${index + 1}. **${course.title}**\n`;
      response += `   ⏱️ ${course.duration} | 🎯 ${course.level} | ⭐ ${course.rating}\n`;
      response += `   💰 ${course.price} | 📚 ${course.category}\n\n`;
    });
    
    response += `Những khóa học này có thể giúp nâng cao EduScore và tăng cơ hội nghề nghiệp. `;
    response += `Bạn đang muốn phát triển kỹ năng nào cụ thể? Tôi có thể đưa ra lộ trình học tập chi tiết!`;
    
    return response;
  }

  // EduScore improvement
  if (lowerPrompt.includes('eduscore') || lowerPrompt.includes('score') || lowerPrompt.includes('improve') || lowerPrompt.includes('cải thiện')) {
    let response = ``;
    
    if (eduscoreContext?.eduscore) {
      response += `Với EduScore ${eduscoreContext.eduscore}/100 hiện tại, bạn `;
      if (eduscoreContext.eduscore >= 80) {
        response += `đang có thành tích rất tốt! Để đạt mức cao hơn nữa:\n\n`;
      } else if (eduscoreContext.eduscore >= 60) {
        response += `có tiềm năng cải thiện đáng kể. Đây là cách:\n\n`;
      } else {
        response += `cần tập trung cải thiện để mở ra nhiều cơ hội hơn:\n\n`;
      }
    } else {
      response += `EduScore là chỉ số quan trọng đánh giá năng lực toàn diện của bạn. Để cải thiện:\n\n`;
    }
    
    response += `📚 **Thành tích học tập (40%)**\n`;
    response += `- Upload bảng điểm, chứng chỉ chính thức\n`;
    response += `- Hoàn thành các khóa học online có chứng nhận\n`;
    response += `- Tham gia cuộc thi học thuật\n\n`;
    
    response += `🔧 **Kỹ năng chuyên môn (30%)**\n`;
    response += `- Bổ sung kỹ năng IT: Python, Java, React\n`;
    response += `- Chứng chỉ quốc tế: AWS, Google Analytics, Microsoft\n`;
    response += `- Portfolio dự án thực tế\n\n`;
    
    response += `🌟 **Hoạt động ngoại khóa (20%)**\n`;
    response += `- Tình nguyện viên, leader câu lạc bộ\n`;
    response += `- Thực tập tại doanh nghiệp uy tín\n`;
    response += `- Tham gia hackathon, startup competition\n\n`;
    
    response += `💼 **Kinh nghiệm làm việc (10%)**\n`;
    response += `- Part-time liên quan đến chuyên ngành\n`;
    response += `- Freelance projects\n`;
    response += `- Thư giới thiệu từ giảng viên/nhà tuyển dụng\n\n`;
    
    response += `Bạn muốn tập trung cải thiện khía cạnh nào trước? Tôi có thể đưa ra kế hoạch cụ thể trong 3-6 tháng!`;
    
    return response;
  }

  // Greeting and general responses
  if (lowerPrompt.includes('hello') || lowerPrompt.includes('hi') || lowerPrompt.includes('xin chào') || lowerPrompt.includes('chào')) {
    let response = `Xin chào! Rất vui được gặp bạn! `;
    
    if (eduscoreContext?.eduscore) {
      response += `Tôi thấy bạn có EduScore ${eduscoreContext.eduscore}/100`;
      if (eduscoreContext.major) {
        response += ` và đang học ${eduscoreContext.major}`;
      }
      response += `. Điều này thật tuyệt vời!\n\n`;
    } else {
      response += `Tôi là trợ lý AI chuyên về giáo dục và tài chính tại Việt Nam.\n\n`;
    }
    
    response += `Hôm nay tôi có thể giúp bạn về:\n`;
    response += `🎓 **Học bổng và tài trợ học tập**\n`;
    response += `💼 **Cơ hội việc làm và định hướng nghề nghiệp**\n`;
    response += `💰 **Tư vấn tài chính và đầu tư cho sinh viên**\n`;
    response += `📚 **Khóa học và phát triển kỹ năng**\n`;
    response += `📊 **Cải thiện EduScore và hồ sơ cá nhân**\n\n`;
    
    response += `Bạn quan tâm đến chủ đề nào nhất? Hay có thắc mắc cụ thể nào tôi có thể giúp?`;
    
    return response;
  }

  // Default conversational response
  let response = `Cảm ơn bạn đã chia sẻ! `;
  
  if (history.length > 0) {
    response += `Tôi hiểu bạn đang tìm hiểu về nhiều khía cạnh khác nhau. `;
  }
  
  response += `Với kinh nghiệm tư vấn giáo dục tại Việt Nam, tôi có thể hỗ trợ bạn về:\n\n`;
  response += `📈 **Phân tích tài chính chi tiết**: Lãi suất vay học, đầu tư, ngân sách sinh viên\n`;
  response += `🎯 **Định hướng nghề nghiệp**: Dựa trên xu hướng thị trường 2024-2025\n`;
  response += `🏆 **Học bổng và cơ hội**: Phù hợp với năng lực và nguyện vọng\n\n`;
  
  if (eduscoreContext?.eduscore) {
    response += `Với EduScore ${eduscoreContext.eduscore}/100 và profile hiện tại của bạn, tôi có thể đưa ra lời khuyên rất cụ thể. `;
  }
  
  response += `Bạn muốn đi sâu vào chủ đề nào? Tôi sẵn sàng phân tích và tư vấn chi tiết!`;
  
  return response;
}

function generateIntelligentResponse(prompt: string, eduscore?: number): string {
  const lowerPrompt = prompt.toLowerCase();
  
  if (lowerPrompt.includes('scholarship') || lowerPrompt.includes('funding') || lowerPrompt.includes('grant')) {
    const eligibleScholarships = eduscore 
      ? scholarships.filter(s => s.minEduscore <= eduscore)
      : scholarships.slice(0, 3);
    
    let response = `Based on ${eduscore ? `your EduScore of ${eduscore}` : 'your profile'}, here are some great scholarship opportunities:\n\n`;
    
    eligibleScholarships.forEach((scholarship, index) => {
      response += `${index + 1}. **${scholarship.name}**\n`;
      response += `   • Provider: ${scholarship.provider}\n`;
      response += `   • Amount: $${scholarship.amount.toLocaleString()}\n`;
      response += `   • Min EduScore: ${scholarship.minEduscore}\n\n`;
    });
    
    response += "Would you like more details about any of these scholarships or help with applications?";
    return response;
  }
  
  if (lowerPrompt.includes('course') || lowerPrompt.includes('learn') || lowerPrompt.includes('study')) {
    let response = "Here are some excellent courses that might interest you:\n\n";
    
    courses.slice(0, 4).forEach((course, index) => {
      response += `${index + 1}. **${course.title}**\n`;
      response += `   • Category: ${course.category}\n`;
      response += `   • Price: ${course.price}\n`;
      response += `   • Rating: ${course.rating}⭐\n\n`;
    });
    
    response += "These courses can help boost your EduScore and career prospects!";
    return response;
  }
  
  if (lowerPrompt.includes('job') || lowerPrompt.includes('intern') || lowerPrompt.includes('career')) {
    let response = "Here are some great job and internship opportunities:\n\n";
    
    jobs.forEach((job, index) => {
      response += `${index + 1}. **${job.title}**\n`;
      response += `   • Company: ${job.company}\n`;
      response += `   • Location: ${job.location}\n`;
      response += `   • Type: ${job.type}\n\n`;
    });
    
    response += "Would you like tips on how to apply or prepare for interviews?";
    return response;
  }
  
  if (lowerPrompt.includes('eduscore') || lowerPrompt.includes('score') || lowerPrompt.includes('improve')) {
    return `Your current EduScore is ${eduscore || 'not yet calculated'}. Here are ways to improve it:

📚 **Academic Excellence**
• Upload transcripts and certificates
• Complete relevant courses and certifications
• Maintain good grades

🔍 **Skills Development**  
• Add verified skills to your profile
• Get endorsements from peers and mentors
• Complete skill assessments

🌟 **Extracurricular Activities**
• Participate in volunteer work
• Join professional organizations
• Lead community projects

💼 **Professional Experience**
• Document internships and work experience
• Get recommendation letters
• Build a strong portfolio

Each verified element increases your EduScore and scholarship eligibility!`;
  }
  
  // Default helpful response
  return `Hello! I'm your AI advisor for education and career guidance. I can help you with:

🎓 **Scholarships** - Find funding opportunities matching your profile
📚 **Courses** - Discover learning opportunities to boost your skills  
💼 **Jobs & Internships** - Explore career opportunities
📊 **EduScore** - Tips to improve your academic scoring

What would you like to explore today? Just ask me about any of these topics!`;
}

export async function processAIChat(request: ChatRequest): Promise<string> {
  console.log('🔄 processAIChat called with:', {
    prompt: request.prompt?.substring(0, 100) + '...',
    historyLength: request.history?.length || 0,
    userId: request.userId || 'none'
  });

  try {
    // Get user's EduScore profile if available (server-side safe)
    let eduscoreContext = null;
    try {
      // Only try to get EduScore context if we're on client side
      if (typeof window !== 'undefined') {
        const { EduscoreService } = await import('./eduscore-service');
        eduscoreContext = EduscoreService.getRecommendationContext();
      }
    } catch (eduscoreError) {
      console.log('📊 EduScore service not available on server side');
    }
    console.log('📊 EduScore context:', eduscoreContext ? 'found' : 'not found');
    
    // Build comprehensive Vietnamese system instruction with icon support
    let systemInstruction = `### Bạn là Hyhan - người bạn đồng hành AI, chuyên cung cấp thông tin và tư vấn cá nhân hóa cho học sinh, sinh viên về các cơ hội học tập, phát triển sự nghiệp và hỗ trợ tài chính.

### ĐỊNH HƯỚNG GIAO TIẾP, CÁCH TRẢ LỜI:
- Thân thiện và gần gũi: Xưng hô "mình" - "bạn", "Hyhan" - "bạn" hoặc "tôi" - "bạn" tùy ngữ cảnh, luôn sử dụng giọng điệu tích cực, động viên và dễ tiếp cận.
- Chuyên nghiệp và rõ ràng: Trả lời trực tiếp vào câu hỏi, tránh lan man.
- Cấu trúc phản hồi:
+ Phần mở đầu: Bắt đầu bằng lời chào thân thiện, thể hiện sự thấu hiểu câu hỏi của người dùng.
+ Nội dung chính: Liệt kê các thông tin một cách khoa học, sử dụng các tiêu đề, danh sách (list), và in đậm (bold) để làm nổi bật thông tin quan trọng.
+ Phần kết: Kết thúc bằng một câu hỏi mở để khuyến khích người dùng tiếp tục tương tác, hoặc một lời chúc tốt đẹp.

### CÁC QUY TẮC TRÌNH BÀY:
- Ở đầu các nội dung chính, mục chính thì sử dụng icon để tăng tính trực quan:
  + 🎓 cho học bổng và tài trợ học tập
  + 📚 cho khóa học và chương trình đào tạo
  + 💼 cho việc làm và cơ hội nghề nghiệp
  + 💰 cho tư vấn tài chính và đầu tư
  + 📊 cho phân tích EduScore và cải thiện hồ sơ
  + ✨ cho lời khuyên và gợi ý
- Sử dụng in đậm (**text**) cho các thông tin quan trọng
- Sử dụng danh sách có dấu đầu dòng (-) để liệt kê thông tin
- Tránh để khoảng trống dư thừa giữa các dòng`;

    if (eduscoreContext) {
      systemInstruction += `

User profile:
- EduScore: ${eduscoreContext.eduscore}/100
- Major: ${eduscoreContext.major || 'Not specified'}  
- Year: ${eduscoreContext.currentYear || 'Not specified'}
- Skills: ${eduscoreContext.technicalSkills?.join(', ') || 'Not specified'}
- Goals: ${eduscoreContext.careerGoals || 'Not specified'}

Personalize your responses using this information.`;
    }

    systemInstruction += `

Respond conversationally with detailed, helpful advice. Ask follow-up questions to better understand their needs.`;

    // Build conversation messages for Gemini
    const conversationHistory = request.history.map(msg => ({
      role: msg.role === 'user' ? 'user' : 'model',
      content: msg.content
    }));

    // Combine system instruction with conversation  
    let messages;
    if (conversationHistory.length === 0) {
      // First message - include system instruction
      messages = [
        { role: 'user', content: systemInstruction + '\n\nUser question: ' + request.prompt }
      ];
    } else {
      // Ongoing conversation - include system instruction with history
      messages = [
        { role: 'user', content: systemInstruction },
        { role: 'model', content: 'I understand. I\'ll provide personalized, conversational guidance for Vietnamese students.' },
        ...conversationHistory,
        { role: 'user', content: request.prompt }
      ];
    }

    // Use Google Gemini API with the correct environment variable from .env.local
    const apiKey = process.env.GOOGLE_GENAI_API_KEY || process.env.GOOGLE_AI_API_KEY || process.env.GEMINI_API_KEY;
    
    if (!apiKey) {
      console.error('❌ No Google AI API key found!');
      console.error('Please add GOOGLE_GENAI_API_KEY to your .env.local file');
      throw new Error('API key required for AI functionality');
    }

    console.log('✅ Found API key, calling Google Gemini API...');
    
    try {
      const response = await callGoogleAI(messages, apiKey);
      console.log('✅ Gemini API response length:', response?.length);
      
      if (response && response.length > 10) {
        console.log('✅ Successfully got response from Gemini API');
        return response;
      } else {
        console.error('❌ Gemini API returned empty/short response:', response);
        throw new Error('Empty response from Gemini API');
      }
    } catch (apiError) {
      console.error('❌ Gemini API error:', apiError);
      console.error('Error details:', apiError.message);
      
      // Re-throw the error so it gets handled properly
      throw new Error(`Gemini API failed: ${apiError.message}`);
    }

  } catch (error) {
    console.error('❌ Error processing AI chat:', error);
    console.error('Error details:', error.message);
    
    // If Gemini API fails, still provide an intelligent response but indicate the issue
    console.log('🔄 Gemini API unavailable, using enhanced local responses');
    
    // Try to get EduScore context safely for fallback
    let fallbackEduscoreContext = null;
    try {
      if (typeof window !== 'undefined') {
        const { EduscoreService } = await import('./eduscore-service');
        fallbackEduscoreContext = EduscoreService.getRecommendationContext();
      }
    } catch (eduscoreError) {
      console.log('📊 EduScore service not available for fallback');
    }
    
    // Add a note about API availability
    const fallbackResponse = generateEnhancedResponse(request.prompt, request.history, fallbackEduscoreContext);
    return `${fallbackResponse}\n\n*Note: AI service is temporarily using local responses. Full AI features will be available when the API connection is restored.*`;
  }
}